Feature/camera
umgc/fall2023 pull request #26
Opened 2023-10-19 22:44 UTC by HiRichard

Updated with rear camera initialization, auto recording, timer, and some tweaks.

2023-10-19 23:39 UTC, vinceg2012 approved these changes

2023-10-20 03:51 UTC, BenjaminSutter approved these changes, later dismissed
Solid organization and refactor.

2023-10-20 04:00 UTC, BenjaminSutter requested changes
We want the recording to start when the app is opened, not just when they go to the video recording tab. Also, it looks like the timer was going double speed (every second the count would go up by 2 seconds).

To accomplish this, we may want to extract the camera functionality into a separate class.

2023-10-24 15:11 UTC, BenjaminSutter approved these changes

2023-10-24 15:15 UTC, merged