Feature/image display sig obj
umgc/fall2023 pull request #44
Opened 2023-10-25 01:10 UTC by Selam2121

2023-10-25 16:54 UTC, zcappella commented on cogniopenapp/linux/flutter/generated_plugin_registrant.cc
All of these generated files should be being ingnored in the .gitignore

2023-10-25 16:55 UTC, zcappella requested changes
We need to remove the added files that were previously being ignored by the .gitignore. All of the generated dynamic code.

2023-10-27 03:53 UTC, BenjaminSutter approved these changes

2023-10-27 09:19 UTC, zcappella approved these changes

2023-10-27 09:19 UTC, merged